#!/usr/bin/env python3

import sys
import subprocess

def check_factor(result):
    args = result.split()
    num1 = int(args[1])
    num2 = int(args[2])

    if num2 > num1:
        num1, num2 = num2, num1

    print(f"{args[0]}={num1}*{num2}")

def main():
    if len(sys.argv) != 2:
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            num = int(line.strip())
            result = subprocess.run(["factor", str(num)], capture_output=True, text=True)
            check_factor(result.stdout)

if __name__ == "__main__":
    main()
