#!/usr/bin/env python3

import sys
import subprocess
import math

def check_factor(result):
    if len(result) != 3:
        args = result
        count = 0
        num2 = 1
        for a in args:
            if count > 1:
                num2 *= a
            count += 1
    else:
        num2 = result[2]

    num1 = result[1]
    num = f"{result[0]}={num1}"

    if num2 > num1:
        num1, num2 = num2, num1

    print(f"{num}*{num2}")

def main():
    if len(sys.argv) != 2:
        print('Usage: rsa <file>')
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            num = int(line.strip())
            result = subprocess.run(["factor", str(num)], capture_output=True, text=True)
            factors = [int(x.rstrip(':')) for x in result.stdout.split()]
            check_factor(factors)

if __name__ == "__main__":
    main()
